// <auto-generated />
using EventosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventosApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221214184058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventosApi.Models.Balada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bebida")
                        .HasColumnType("bit");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Entrada")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("baladas");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Bebida = true,
                            Endereco = "Avenida Nova",
                            Entrada = 30f,
                            Nome = "Red"
                        },
                        new
                        {
                            Id = 3,
                            Bebida = true,
                            Endereco = "Avenida Engenheiro",
                            Entrada = 20f,
                            Nome = "Lux"
                        },
                        new
                        {
                            Id = 4,
                            Bebida = true,
                            Endereco = "Avenida Nova",
                            Entrada = 10f,
                            Nome = "Barcelona"
                        },
                        new
                        {
                            Id = 5,
                            Bebida = true,
                            Endereco = "Avenida Cruzeiro",
                            Entrada = 60f,
                            Nome = "Dubai"
                        },
                        new
                        {
                            Id = 6,
                            Bebida = true,
                            Endereco = "Avenida Guilherme",
                            Entrada = 25f,
                            Nome = "Slim"
                        },
                        new
                        {
                            Id = 1,
                            Bebida = true,
                            Endereco = "Santana",
                            Entrada = 0f,
                            Nome = "Robinho"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
